---
all:
  children:
    nodes:
      hosts:
        odin:
          ansible_host: 192.168.50.20
          hostname: odin
        # thor:
        #   ansible_host: 192.168.1.101  # Update with thor's IP
        #   hostname: thor
  vars:
    ansible_python_interpreter: /usr/bin/python3
