- name: Home
  columns:
    - size: small
      widgets:
        - type: bookmarks
          groups:
            - title: Work
              links:
                - title: GitHub Project
                  url: ${GITHUB_PROJECT_URL}
                  icon: di:github-light.svg
                - title: Harvest
                  url: ${HARVEST_URL}
                  icon: di:bitcoin.svg
                - title: Quickbooks
                  url: ${QUICKBOOKS_URL}
                  icon: si:quickbooks

            - title: Tools
              links:
                - title: Kagi Assistant
                  url: https://kagi.com/assistant
                  icon: di:kagi.svg
                - title: IT Tools
                  url: https://it-tools.tech/
                  icon: di:it-tools-light.svg
                - title: Selfh.st
                  url: https://selfh.st/apps/
                  icon: di:selfh-st.svg

            - title: Entertainment
              links:
                - title: YouTube
                  url: https://www.youtube.com/
                  icon: si:youtube.svg
                - title: Twitch
                  url: https://www.twitch.tv/
                  icon: si:twitch.png

    - size: full
      widgets:
        - type: search
          autofocus: true
          search-engine: duckduckgo

        - type: group
          title: Services
          widgets:
            - type: docker-containers
              title: Docker
              hide-by-default: true
              containers:
                dockhand:
                  name: Dockhand
                  description: Docker Stack Manager
                  url: https://dockhand.${BASE_URL}
                  icon: di:dockhand.png
                  hide: false
                birdnet-go:
                  name: BirdNET
                  description: Bird Song Identification
                  url: https://birdnet.${BASE_URL}
                  icon: di:birdnet.png
                  hide: false
                readeck:
                  name: Readeck
                  description: Read-It-Later
                  url: https://readeck.${BASE_URL}
                  icon: di:readeck
                  hide: false

            - type: monitor
              cache: 1m
              title: System
              sites:
                - title: Home Assistant
                  url: https://homeassistant.${BASE_URL}
                  check-url: http://host.docker.internal:8123
                  icon: di:home-assistant
                - title: Cockpit
                  url: https://cockpit.${BASE_URL}
                  check-url: https://host.docker.internal:9090
                  icon: di:cockpit
                  allow-insecure: true

        - type: videos
          style: grid-cards
          collapse-after-rows: 3
          channels:
            - UCNvzD7Z-g64bPXxGzaQaa4g # gameranx
            - UCZ7AeeVbyslLM_8-nVy2B8Q # Skill Up
            - UC9PBzalIcEQCsiIkq36PyUA # Digital Foundry

    - size: small
      widgets:
        - type: twitch-channels
          collapse-after: 15
          sort-by: viewers
          channels:
            - cohhcarnage
            - dansgaming
            - bobross
            - theprimeagen
